EasyRight/EasyRight/Controllers/OperationController.cs
using EasyRight.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EasyRight.Controllers
{
    public class OperationController : Controller
    {
        //
        // GET: /Operation/

        public ActionResult Index(Guid rid)
        {
            var role = ERRepositry.Instance.GetRoleById(rid);
            var roleOpers = role.GetOperations().Select(o => o.Id);

            var opers = ERRepositry.Instance.GetOperations();
            foreach (var oper in opers)
            {
                if (roleOpers.Contains(oper.Id))
                {
                    oper.IsSelected = true;
                }
            }

            return View(opers);
        }

        [HttpPost]
        public ActionResult Index(FormCollection form)
        {
            Guid rid = Guid.Parse(Request.QueryString["rid"]);
            var role = ERRepositry.Instance.GetRoleById(rid);

            var opers = ERRepositry.Instance.GetOperations();
            var roleOperations = opers.Where(o => form.Keys.Cast<string>()
                                                            .Select(s => Guid.Parse(s))
                                                            .Contains(o.Id)).ToList();
            
            ERRepositry.Instance.RefreshRoleOperations(role, roleOperations);

            ViewBag.Message = "Operation Success";

            return Index(rid);
        }
    }
}

EasyRight/EasyRight/Controllers/RoleController.cs
using EasyRight.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EasyRight.Controllers
{
    public class RoleController : Controller
    {
        //
        // GET: /Role/

        public ActionResult Index()
        {
            var Roles = ERRepositry.Instance.GetRoles();

            return View(Roles);
        }


        //
        // GET: /Role/Details/5

        public ActionResult Details(Guid id)
        {
            var Role = ERRepositry.Instance.GetRoleById(id);
            return View(Role);
        }

        //
        // GET: /Role/Create

        public ActionResult Create()
        {
            ERRole Role = new ERRole();
            return View(Role);
        }

        //
        // POST: /Role/Create

        [HttpPost]
        public ActionResult Create(ERRole Role)
        {
            try
            {
                ERRepositry.Instance.AddRole(Role);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Role/Edit/5

        public ActionResult Edit(Guid id)
        {
            var Role = ERRepositry.Instance.GetRoleById(id);
            return View(Role);
        }

        //
        // POST: /Role/Edit/5

        [HttpPost]
        public ActionResult Edit(Guid id, ERRole Role)
        {
            try
            {
                ERRepositry.Instance.UpdateRole(Role);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Role/Delete/5

        public ActionResult Delete(Guid id)
        {
            var role = ERRepositry.Instance.GetRoleById(id);
            ERRepositry.Instance.DeleteRole(role);

            return RedirectToAction("Index");
        }

        //
        // POST: /Role/Delete/5

        [HttpPost]
        public ActionResult Delete(Guid id, ERRole Role)
        {
            try
            {
                ERRepositry.Instance.DeleteRole(Role);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult SelectUserRoles(ERUser user)
        {
            var allRoles = ERRepositry.Instance.GetRoles();
            var userRoles = new List<ERRole>();
            if (user != null)
            {
                userRoles = ERRepositry.Instance.GetUserRoles(user);
            }

            ViewBag.AllRoles = allRoles;
            ViewBag.UserRoles = userRoles;

            return PartialView();
        }

    }
}

EasyRight/EasyRight/Views/Role/Create.cshtml
@model EasyRight.Models.ERRole

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>ERRole</legend>

         @Html.EditorForModel()

        <p>
            <input type="submit" value="Create" />
			@Html.ActionLink("Back to List", "Index")
        </p>
    </fieldset>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EasyRight/EasyRight/Views/Role/Delete.cshtml
@model EasyRight.Models.ERRole

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>ERRole</legend>
     @Html.DisplayForModel()
    
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

EasyRight/EasyRight/Views/Role/Details.cshtml
@model EasyRight.Models.ERRole

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>ERRole</legend>

     @Html.DisplayForModel()
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

EasyRight/EasyRight/Views/Role/Edit.cshtml
@model EasyRight.Models.ERRole

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>ERRole</legend>

        @Html.EditorForModel()

        <p>
            <input type="submit" value="Save" />
			@Html.ActionLink("Back to List", "Index")
        </p>
    </fieldset>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EasyRight/EasyRight/Views/Role/Index.cshtml
@model IEnumerable<EasyRight.Models.ERRole>

@{
    ViewBag.Title = "Index";
}

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="DefaultTableStyle">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Descrption)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Descrption)
            </td>

            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @*  @Html.ActionLink("Details", "Details", new { id=item.Id }) | *@
                @Html.ActionLink("Delete", "Delete", new { id=item.Id }, new { onclick = "return confirm_delete()" })
                @Html.ActionLink("View Rights", "Index", "Operation", new { rid = item.Id },null)
            </td>
        </tr>
}

</table>

EasyRight/EasyRight/Views/Role/SelectUserRoles.cshtml
@using ERRole = EasyRight.Models.ERRole;

@{
    Layout = null;
}

<div>
    <h2>Please select roles</h2>
    <fieldset>
        <legend>Please select roles</legend>        
        @foreach (ERRole item in ViewBag.AllRoles)
        {
            bool selected = ((List<ERRole>)ViewBag.UserRoles).Any(i => i.Id == item.Id);

            <input type="checkbox" id="@item.Id" name="roles" value="@item.Id" @(selected ? "checked='checked'" : "") />
            <label for="@item.Id" class="checkbox">@item.Name</label>
        }
    </fieldset>
</div>